### PR TITLE
[#55] Fix das-node pipeline and create pipeline for python and c++ tests

### LINKED ISSUE #55: Fix das-node pipeline and create pipeline for python and c++ tests

### PR DESCRIPTION
**Pull request by levisingularity**
Closes #55

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -13,7 +13,7 @@ cpp-test:
 wheeler-image:
 	@./scripts/wheeler_image.sh
 
-wheeler-build:
+wheeler-build:
```
Comment (Pedrobc89) [inline Makefile:16]: Can you get rid of this empty space?

File: scripts/wheeler_test.sh [hunk 2]
```diff
@@ -9,7 +9,7 @@ CONTAINER_NAME="das-node-wheeler-test"
 docker run \
   --rm \
   --name=$CONTAINER_NAME \
-  --mount type=volume,source=bazel_cache,target=/root/.cache/bazel \
+  --volume ./docker/volumes/bazel_cache:/root/.cache/bazel \
```
Comment (Pedrobc89) [inline scripts/wheeler_test.sh:12]: Is there any reason for this change? Just want to understand it, not particularly against it.

**Review by Pedrobc89 — APPROVED** [review]
One typo I believe, and on open question.
It does looks good to me though.

File: scripts/wheeler_test.sh (hunk 2 above)
Comment (levisingularity) [reply scripts/wheeler_test.sh:12]: Yes, when a Docker volume is created, its mount point is located inside /var. Since I'm using actions/cache to share the volume globally in the pipeline, this setup was causing permission issues. That's why I switched to a bind mount instead, as it lets me set the mount point to a directory within the working directory, avoiding these kinds of issues.

**Review by andre-senna — APPROVED** [review]
